{{- if .Values.configuration -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-cm
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  config.toml: | 
    {{- tpl .Values.configuration . | nindent 4 }}
{{- end -}}